select count(*) from NATIONAL_FACILITY_FILE where STATE_CODE ='UT'


select distinct STATE_CODE from NATIONAL_FACILITY_FILE

SELECT *
INTO UT_EPA
FROM NATIONAL_FACILITY_FILE
where STATE_CODE ='UT'


SELECT [LATITUDE83],[LONGITUDE83] , COUNT([LATITUDE83]) as count 
FROM UT_EPA
GROUP BY [LATITUDE83],[LONGITUDE83]
HAVING COUNT([LONGITUDE83]) >1

select * from UT_EPA where Dups ='1'

alter table UT_EPA add  Dups varchar(200)

WITH cte AS
(
	SELECT *,ROW_NUMBER() OVER (PARTITION BY LATITUDE83 ORDER BY [REGISTRY_ID]) AS RN from UT_EPA
)
-- select * from cte where RN=1;
UPDATE cte SET Dups = 1 WHERE RN=1;

